repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true

    - id: terraform_fmt
      args:
        - --args=-write=true
        - --args=-recursive

    - id: terraform_validate
      args:
        - --args=-json

    - id: terraform_tflint
      args:
        - --args=--loglevel=trace
        - --args=--enable-rule=terraform_documented_variables
        - --args=--module

#    - id: checkov
#      args: [
#        "-d", "./terraform",
#        "--framework", "terraform"
#      ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: detect-aws-credentials
  - id: detect-private-key
