---

name: Plan / Test on PR

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive ./

  environment:
    name: environment
    runs-on: ubuntu-latest
    steps:
      - name: Set env to development
        if: endsWith(github.ref, '/development')
        run: |
          echo "::set-env name=ENVIRONMENT::development"

      - name: set env to stage
        if: endsWith(github.ref, '/stage')
        run: |
          echo "::set-env name=ENVIRONMENT::stage"

      - name: set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "::set-env name=ENVIRONMENT::production"

    plan:
      name: plan
      runs-on: ubuntu-latest
      environment:
        name: ${{ env.ENVIRONMENT }}
        url: https://github.com
      strategy:
        fail-fast: false
        matrix:
          path:
            - us-east-1
            - 
